// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeIndicator: typeof import('./src/components/Simulator/HomeIndicator.vue')['default']
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IEpBox: typeof import('~icons/ep/box')['default']
    IEpCaretBottom: typeof import('~icons/ep/caret-bottom')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpFolderOpened: typeof import('~icons/ep/folder-opened')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    NavigationBar: typeof import('./src/components/Simulator/NavigationBar.vue')['default']
    Notch: typeof import('./src/components/Simulator/Notch.vue')['default']
    Page: typeof import('./src/components/Simulator/Page.vue')['default']
    Service: typeof import('./src/components/Simulator/Service.vue')['default']
    Simulator: typeof import('./src/components/Simulator/Simulator.vue')['default']
    SplitView: typeof import('./src/components/SplitView.vue')['default']
    Startup: typeof import('./src/components/Startup/Startup.vue')['default']
    StatusBar: typeof import('./src/components/Simulator/StatusBar.vue')['default']
    TabBar: typeof import('./src/components/Simulator/TabBar.vue')['default']
    ToolsBar: typeof import('./src/components/ToolsBar.vue')['default']
    WebView: typeof import('./src/components/Simulator/WebView.vue')['default']
  }
}
