export const enum Events {
  INIT_ENV = 'INIT_ENV',
  API_INVOKE = 'API_INVOKE',
  RELOAD = 'RELOAD',
  /** 打开项目所在的文件夹 */
  OPEN_DIRECTORY_PROJECT = 'OPEN_DIRECTORY_PROJECT',
  /** 打开项目 */
  OPEN_PROJECT = 'OPEN_PROJECT',
  /** 选择创建项目保存在什么地方 */
  SELECT_PROJECT_DESTINATION_DIRECTORY = 'SELECT_PROJECT_DESTINATION_DIRECTORY',
  SHOW_DEVICE_MENU = 'SHOW_DEVICE_MENU',
  DEVICE_MENU_COMMAND = 'DEVICE_MENU_COMMAND',
  OPEN_DEVTOOLS = 'OPEN_DEVTOOLS',
  SET_WEBVIEW_CONTENTS_ID = 'SET_WEBVIEW_CONTENTS_ID',
  GET_STORE_VALUE = 'GET_STORE_VALUE',
  SET_STORE_VALUE = 'SET_STORE_VALUE',
  SHOW_PROJECT_MENU = 'SHOW_PROJECT_MENU',
}
